version: '2'
services:
    hipstershares-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/hipsterShares/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hipsterShares
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
