version: '2'
services:
  jhipster:
    container_name: jhipster
    image: jhipster/jhipster
    ports:
     - 8080:8080
     - 3000:3000
     - 3001:3001
    volumes:
     - ~/workspace/hipsterShares:/home/jhipster/app
     - ~/.m2:/home/jhipster/.m2
     